// dummyData.ts (or .js)

// 👉 /map mock (matches your code: dummyData.data.randomStores)
const dummyData = {
  code: 'OK',
  message: 'Request succeeded.',
  success: true,
  data: {
    marketOptions: [
      { name: 'Yongsan Yongmun Market', id: 1 },
      { name: 'Itaewon Market', id: 2 },
      { name: 'Huam Traditional Market', id: 3 },
      { name: 'Manri Market', id: 4 },
      { name: 'Haebangchon Sinheung Market', id: 5 },
    ],
    categoryOptions: [
      {
        mainCategoryId: 1,
        mainCategoryName: 'Agri-Fishery & Food',
        subCategories: [
          { name: 'Fruits & Vegetables', id: 1 },
          { name: 'Seafood', id: 2 },
          { name: 'Meat & Livestock', id: 3 },
          { name: 'Grains', id: 4 },
          { name: 'Side Dishes', id: 5 },
          { name: 'Rice Cakes & Bakery', id: 6 },
        ],
      },
      {
        mainCategoryId: 2,
        mainCategoryName: 'Restaurants & Cafés',
        subCategories: [
          { name: 'Korean Cuisine', id: 7 },
          { name: 'Korean Snacks', id: 8 },
          { name: 'Sashimi & Seafood', id: 9 },
          { name: 'World Cuisine', id: 10 },
          { name: 'Fusion Cuisine', id: 11 },
          { name: 'Cafés & Tea', id: 12 },
        ],
      },
      {
        mainCategoryId: 3,
        mainCategoryName: 'Pubs & Bars',
        subCategories: [
          { name: 'Korean Traditional Pub', id: 13 },
          { name: 'Beer Hall', id: 14 },
          { name: 'Bar', id: 15 },
          { name: 'Izakaya', id: 16 },
        ],
      },
      {
        mainCategoryId: 4,
        mainCategoryName: 'General Goods & Daily Supplies',
        subCategories: [
          { name: 'Clothing & Shoes', id: 17 },
          { name: 'Daily Goods', id: 18 },
          { name: 'Home Goods', id: 19 },
        ],
      },
      {
        mainCategoryId: 5,
        mainCategoryName: 'Souvenirs, Crafts & Hanbok',
        subCategories: [
          { name: 'Souvenir Shop', id: 20 },
          { name: 'Hanbok & Traditional Wear', id: 21 },
          { name: 'Handicrafts', id: 22 },
          { name: 'Accessory Shop', id: 23 },
        ],
      },
      {
        mainCategoryId: 6,
        mainCategoryName: 'Services & Others',
        subCategories: [],
      },
    ],
    randomStores: [
      {
        id: 101,
        name: 'Egg & Flower',
        isOpen: true,
        subCategories: ['World Cuisine'],
        address: '35, Sinheung-ro 26-gil, Yongsan-gu, Seoul',
        phone: '0507-1328-7681',
        image: 'https://example.com/images/egg-flower.jpg',
      },
      {
        id: 102,
        name: 'Seoul Gukbap',
        isOpen: false,
        subCategories: ['Korean Cuisine'],
        address: '100, Cheongpa-ro 47-gil, Yongsan-gu, Seoul',
        phone: '010-0000-0000',
        image: 'https://example.com/images/seoul-gukbap.jpg',
      },
      {
        id: 103,
        name: 'Itaewon Bakery',
        isOpen: true,
        subCategories: ['Rice Cakes & Bakery'],
        address: '22, Itaewon-ro, Yongsan-gu, Seoul',
        phone: '02-123-4567',
        image: 'https://example.com/images/itaewon-bakery.jpg',
      },
    ],
  },
}

// 👉 /map/filter mock (keys use lat/lng to match your marker code)
export const mapFilterMock = {
  code: 'OK',
  message: 'Request succeeded.',
  success: true,
  data: [
    // ===== Market 1: Yongsan Yongmun Market =====
    {
      id: 201,
      marketId: 1,
      name: 'Yongmun Butcher',
      isOpen: true,
      subCategories: ['Meat & Livestock'],
      address: 'Yongmun Market, Yongsan-gu, Seoul',
      phone: '02-111-2222',
      image: 'https://example.com/images/yongmun-butcher.jpg',
      lat: 37.5369,
      lng: 126.9596,
    },
    {
      id: 202,
      marketId: 1,
      name: 'Yongmun Veggies',
      isOpen: true,
      subCategories: ['Fruits & Vegetables'],
      address: 'Yongmun Market, Yongsan-gu, Seoul',
      phone: '02-222-3333',
      image: 'https://example.com/images/yongmun-veggies.jpg',
      lat: 37.53645,
      lng: 126.95995,
    },
    {
      id: 203,
      marketId: 1,
      name: 'Yongmun Banchan',
      isOpen: false,
      subCategories: ['Side Dishes'],
      address: 'Yongmun Market, Yongsan-gu, Seoul',
      phone: '02-333-4444',
      image: 'https://example.com/images/yongmun-banchan.jpg',
      lat: 37.5362,
      lng: 126.9602,
    },

    // ===== Market 2: Itaewon Market =====
    {
      id: 204,
      marketId: 2,
      name: 'Itaewon Café Nimbus',
      isOpen: true,
      subCategories: ['Cafés & Tea'],
      address: 'Itaewon-ro, Yongsan-gu, Seoul',
      phone: '02-444-5555',
      image: 'https://example.com/images/itaewon-cafe.jpg',
      lat: 37.5341,
      lng: 126.9902,
    },
    {
      id: 205,
      marketId: 2,
      name: 'Itaewon BBQ House',
      isOpen: true,
      subCategories: ['Korean Cuisine'],
      address: 'Itaewon-ro, Yongsan-gu, Seoul',
      phone: '02-555-6666',
      image: 'https://example.com/images/itaewon-bbq.jpg',
      lat: 37.5337,
      lng: 126.9898,
    },
    {
      id: 206,
      marketId: 2,
      name: 'Itaewon Bakery',
      isOpen: true,
      subCategories: ['Rice Cakes & Bakery'],
      address: 'Itaewon-ro, Yongsan-gu, Seoul',
      phone: '02-123-4567',
      image: 'https://example.com/images/itaewon-bakery.jpg',
      lat: 37.5335,
      lng: 126.9904,
    },

    // ===== Market 3: Huam Traditional Market =====
    {
      id: 207,
      marketId: 3,
      name: 'Huam Seafood',
      isOpen: true,
      subCategories: ['Seafood'],
      address: 'Huam-dong, Yongsan-gu, Seoul',
      phone: '02-222-3333',
      image: 'https://example.com/images/huam-seafood.jpg',
      lat: 37.5502,
      lng: 126.9761,
    },
    {
      id: 208,
      marketId: 3,
      name: 'Huam Kimbap',
      isOpen: false,
      subCategories: ['Korean Snacks'],
      address: 'Huam-dong, Yongsan-gu, Seoul',
      phone: '02-777-8888',
      image: 'https://example.com/images/huam-kimbap.jpg',
      lat: 37.55045,
      lng: 126.9763,
    },
    {
      id: 209,
      marketId: 3,
      name: 'Huam Fried Chicken',
      isOpen: true,
      subCategories: ['Korean Snacks'],
      address: 'Huam-dong, Yongsan-gu, Seoul',
      phone: '02-101-2020',
      image: 'https://example.com/images/huam-chicken.jpg',
      lat: 37.55005,
      lng: 126.97585,
    },

    // ===== Market 4: Manri Market =====
    {
      id: 210,
      marketId: 4,
      name: 'Manri Izakaya',
      isOpen: false,
      subCategories: ['Izakaya'],
      address: 'Manri Market, Yongsan-gu, Seoul',
      phone: '02-333-4444',
      image: 'https://example.com/images/manri-izakaya.jpg',
      lat: 37.5511,
      lng: 126.9635,
    },
    {
      id: 211,
      marketId: 4,
      name: 'Manri Noodle',
      isOpen: true,
      subCategories: ['Korean Cuisine'],
      address: 'Manri Market, Yongsan-gu, Seoul',
      phone: '02-333-9999',
      image: 'https://example.com/images/manri-noodle.jpg',
      lat: 37.55135,
      lng: 126.9634,
    },
    {
      id: 212,
      marketId: 4,
      name: 'Manri General Store',
      isOpen: true,
      subCategories: ['Daily Goods'],
      address: 'Manri Market, Yongsan-gu, Seoul',
      phone: '02-313-1313',
      image: 'https://example.com/images/manri-general.jpg',
      lat: 37.551,
      lng: 126.9638,
    },

    // ===== Market 5: Haebangchon Sinheung Market =====
    {
      id: 213,
      marketId: 5,
      name: 'Egg & Flower',
      isOpen: true,
      subCategories: ['World Cuisine'],
      address: '35, Sinheung-ro 26-gil, Yongsan-gu, Seoul',
      phone: '0507-1328-7681',
      image: 'https://example.com/images/egg-flower.jpg',
      lat: 37.54535,
      lng: 126.9843,
    },
    {
      id: 214,
      marketId: 5,
      name: 'Haebangchon Pizza',
      isOpen: true,
      subCategories: ['World Cuisine'],
      address: 'Sinheung-ro, Yongsan-gu, Seoul',
      phone: '02-454-5454',
      image: 'https://example.com/images/hbc-pizza.jpg',
      lat: 37.5456,
      lng: 126.9847,
    },
    {
      id: 215,
      marketId: 5,
      name: 'HBC Craft Beer',
      isOpen: false,
      subCategories: ['Beer Hall'],
      address: 'Sinheung-ro, Yongsan-gu, Seoul',
      phone: '02-989-8989',
      image: 'https://example.com/images/hbc-beer.jpg',
      lat: 37.5451,
      lng: 126.9851,
    },
  ],
}

export default dummyData
